# # Determine if home
- platform: "bayesian"
  prior: 0.6
  name: "Anthony Home"
  probability_threshold: 0.9
  observations:
    # Wifi Ping (Pixel 4)
    - entity_id: device_tracker.pixel_ping
      platform: state
      prob_given_true: 0.95
      prob_given_false: 0.15
      to_state: home
    # Bluetooth (Pixel 4)
    - entity_id: device_tracker.pixel_bt
      platform: state
      prob_given_true: 0.98
      prob_given_false: 0.4
      to_state: home
    # GPS (Pixel 4)
    - entity_id: device_tracker.pixel_4
      platform: state
      prob_given_true: 0.6
      prob_given_false: 0.1
      to_state: home
    # Tile Keys
    - entity_id: device_tracker.tile_dda2164ee80472f9
      platform: state
      prob_given_true: 0.6
      prob_given_false: 0.1
      to_state: home

# Check network connectivity
- platform: ping
  host: 1.1.1.1
  name: Network
  scan_interval: 30

# Google Home
- platform: ping
  host: 192.168.1.70
  name: Google Home
  scan_interval: 60

# Lights
- platform: template
  sensors:
    main_lights:
      friendly_name: "Main Lights All"
      value_template: >-
        {{ is_state('binary_sensor.kitchen_lights', 'on') 
           and is_state('binary_sensor.living_room_lights', 'on') }}
    kitchen_lights:
      friendly_name: "Kitchen Lights All"
      value_template: >-
        {{ is_state('light.kitchen_left_front', 'on') 
           and is_state('light.kitchen_right_front', 'on') 
           and is_state('light.kitchen_rear', 'on') 
           and is_state('light.entry', 'on') }}
    living_room_lights:
      friendly_name: "Living Room Lights All"
      value_template: >-
        {{ is_state('light.living_room_hanging', 'on') 
           and is_state('light.living_room_dome_left', 'on') 
           and is_state('light.living_room_dome_right', 'on') 
           and is_state('light.hallway', 'on') }}
    office_lights:
      friendly_name: "Office Lights All"
      value_template: >-
        {{ is_state('light.office_dome_left', 'on') 
           and is_state('light.office_dome_right', 'on') 
           and is_state('light.office_lamp_top', 'on') 
           and is_state('light.office_lamp_bottom', 'on') }}
    bedroom_lights:
      friendly_name: "Bedroom Lights All"
      value_template: >-
        {{ is_state('light.bedroom_light_1', 'on') 
           and is_state('light.bedroom_light_2', 'on') }}

    space_heater_connected:
      friendly_name: "Space Heater Connected"
      value_template: >-
        {{ is_state("switch.space_heater_switch", "on") 
          or is_state("switch.space_heater_switch", "off") }}
