homeassistant:
  name: Apartment
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Toronto
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true

  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml

config:

http:
  base_url: !secret ddns_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5

hassio:
mqtt:
  broker: !secret ip_piserver
  port: 1883
  client_id: hassio
  username: !secret mqtt_user
  password: !secret mqtt_pass

recorder:
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

snips:
intent_script: !include intent_script.yaml

homekit:
  filter:
    include_domains:
      - switch
  entity_config:
    switch.front_door:
      name: Front Door

google_assistant:
  project_id: !secret ga_id
  exposed_domains:
    - scene
    - input_boolean

device_tracker: !include device_trackers.yaml

updater:
discovery:
conversation:
history:
logbook:
map:
sun:

python_script:

system_health:

weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily

tts:
  - platform: google_translate
    service_name: google_say
cloud:

ios:

ifttt:
  key: !secret ifttt_key

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# Lights
hue:
  bridges:
    - host: !secret ip_hue_bridge
      allow_unreachable: true
      allow_hue_groups: true

light: !include lights.yaml

scene: !include scenes.yaml

# Media player
media_player: !include media_players.yaml

# Thermostat
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

# Harmony
remote:
  - platform: harmony
    name: Living Room
    host: !secret ip_harmony_livingroom
  - platform: harmony
    name: Office
    host: !secret ip_harmony_office

roku:
  - host: !secret ip_roku

# Switches
switch: !include switch.yaml
tplink:

tuya:
  username: !secret email
  password: !secret tuya_password
  country_code: 1

# Wemo
wemo:
  static:
    - !secret ip_kitchen_lightswitch
    - !secret ip_livingroom_chandelier
    - !secret ip_livingroom_dome
    - !secret ip_office_lightswitch
    - !secret ip_bedroom_lightswitch
    - !secret ip_pc_outlet
    - !secret ip_modem

automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensors.yaml
group: !include_dir_merge_named groups/
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include_dir_merge_named scripts/
sensor: !include sensors.yaml
