homeassistant:
  external_url: !secret ddns_url
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true

  customize: !include customize.yaml

default_config:

frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
  resources:
    - url: /customcards/github/custom-cards/button-card.js?track=true
      type: module
    - url: /local/mini-media-player-bundle.js?v=1.4.2
      type: module
    - url: "https://fonts.googleapis.com/css?family=Raleway"
      type: css

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5

recorder:
  purge_keep_days: 2
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

wake_on_lan:

weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily

ifttt:
  key: !secret ifttt_key

device_tracker: !include device_trackers.yaml

# Google Assistant
google_assistant:
  project_id: !secret ga_id
  service_account: !include homeassistant-e714b.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.fireplace:
      name: "Fireplace"
      room: "Living Room"
      expose: true
    switch.office_heater:
      name: "Office Heater"
      room: "Office"
      expose: true

# Thermostat
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  project_id: !secret nest_project_id

# Lights
light: !include lights.yaml
scene: !include scenes.yaml

# Media player
media_player: !include media_players.yaml
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Switches
switch: !include switch.yaml

# Wemo
wemo:
  static:
    - !secret ip_kitchen_lightswitch
    - !secret ip_livingroom_chandelier
    - !secret ip_livingroom_dome
    - !secret ip_office_lightswitch
    - !secret ip_bedroom_lightswitch
    - !secret ip_pc_outlet

automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensors.yaml
group: !include_dir_merge_named groups/
input_select: !include input_select.yaml
script: !include_dir_merge_named scripts/
python_script:
sensor: !include sensors.yaml
zone: !include zones.yaml
