homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true

  customize: !include customize.yaml

default_config:

frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
  resources:
    - url: /customcards/github/custom-cards/button-card.js?track=true
      type: module
    - url: /local/mini-media-player-bundle.js?v=1.4.2
      type: module
    - url: /local/roku-card.js?v=0
      type: module

http:
  base_url: !secret ddns_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5

mqtt:
  broker: !secret ip_piserver
  port: 1883
  client_id: hassio
  username: !secret mqtt_user
  password: !secret mqtt_pass

recorder:
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

wake_on_lan:

weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily

# Text to speech
tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_key

device_tracker: !include device_trackers.yaml

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret aqara_gateway_key

# Thermostat
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

# Lights
light: !include lights.yaml
scene: !include scenes.yaml

# Media player
media_player: !include media_players.yaml
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Harmony
remote:
  - platform: harmony
    name: Living Room
    host: !secret ip_harmony_livingroom
  - platform: harmony
    name: Office
    host: !secret ip_harmony_office

roku:
  - host: !secret ip_roku

# Switches
switch: !include switch.yaml
tplink:

# Wemo
wemo:
  static:
    - !secret ip_kitchen_lightswitch
    - !secret ip_livingroom_chandelier
    - !secret ip_livingroom_dome
    - !secret ip_office_lightswitch
    - !secret ip_bedroom_lightswitch
    - !secret ip_pc_outlet
    - !secret ip_modem

automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensors.yaml
group: !include_dir_merge_named groups/
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include_dir_merge_named scripts/
python_script:
sensor: !include sensors.yaml

zone: !include zones.yaml
