- platform: tile
  username: !secret email
  password: !secret tile_pass
  monitored_variables: TILE

- platform: ping
  hosts:
    pixel_ping: !secret ip_phone
  new_device_defaults:
    track_new_devices: false

- platform: bluetooth_tracker
