- platform: group
  name: Main
  entities:
    - light.kitchen_left_front
    - light.kitchen_right_front
    - light.kitchen_rear
    - light.entry
    - light.living_room_hanging
    - light.living_room_dome_left
    - light.living_room_dome_right
    - light.hallway

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_left_front
    - light.kitchen_right_front
    - light.kitchen_rear
    - light.entry

- platform: group
  name: Living Room
  entities:
    - light.living_room_hanging
    - light.living_room_dome_left
    - light.living_room_dome_right
    - light.hallway

- platform: group
  name: Office Lights
  entities:
    - light.office_dome_left
    - light.office_dome_right
    - light.office_lamp_top
    - light.office_lamp_bottom

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2

- platform: group
  name: Accent Lights
  entities:
    - light.nanoleaf
    - light.living_room_tv_lightstrip
    - light.living_room_bloom

- platform: flux_led
  devices:
    192.168.1.210:
      name: Christmas Tree

- platform: nanoleaf
  host: !secret ip_nanoleaf
  token: !secret nanoleaf_token
