- platform: systemmonitor
  resources:
    - type: network_in
      arg: "Local Area Connection"
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: last_boot

- platform: template
  sensors:
    current_activity:
      friendly_name: "Current Activity"
      value_template: "{{ state_attr('remote.living_room','current_activity') }}"
    target_temperature:
      friendly_name: "Target Temperature"
      value_template: >
        {% if state_attr('climate.thermostat','temperature') %}
          {{ state_attr('climate.thermostat','temperature') }}
        {% else %}
          24
        {% endif %}
    compare_temp_current_target:
      friendly_name: "Temperature Difference Current-Target"
      value_template: >
        {{ states('sensor.thermostat_temperature') | float
          - states('sensor.target_temperature') | float }}
