- platform: template
  switches:
    living_room_camera:
      friendly_name: Living Room Camera
      value_template: "{{ is_state('camera.living_room','recording') }}"
      turn_on:
        service: camera.turn_on
        data:
          entity_id: camera.living_room
      turn_off:
        service: camera.turn_off
        data:
          entity_id: camera.living_room
      icon_template: >
        {% if is_state('camera.living_room','recording') %}
          mdi:camera
        {% else %}
          mdi:camera-off
        {% endif %}

# Front Door
- platform: mqtt
  name: Front Door
  state_topic: "sonoff/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "sonoff/cmnd/POWER1"
  availability_topic: "sonoff/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false