- platform: template
  switches:
    living_room_camera:
      friendly_name: Living Room Camera
      value_template: "{{ is_state('camera.living_room','recording') }}"
      turn_on:
        service: camera.turn_on
        data:
          entity_id: camera.living_room
      turn_off:
        service: camera.turn_off
        data:
          entity_id: camera.living_room
      icon_template: >
        {% if is_state('camera.living_room','recording') %}
          mdi:camera
        {% else %}
          mdi:camera-off
        {% endif %}