- platform: template
  switches:
    # Living Room Camera
    living_room_camera:
      friendly_name: Living Room Camera
      value_template: "{{ is_state('camera.living_room','recording') }}"
      turn_on:
        service: camera.turn_on
        data:
          entity_id: camera.living_room
      turn_off:
        service: camera.turn_off
        data:
          entity_id: camera.living_room
      icon_template: >
        {% if is_state('camera.living_room','recording') %}
          mdi:camera
        {% else %}
          mdi:camera-off
        {% endif %}

    # Fireplace
    fireplace:
      friendly_name: Fireplace
      value_template: "{{ is_state('remote.living_room', 'Fireplace') }}"
      turn_on:
        service: remote.send_command
        target:
          entity_id: remote.living_room
        data:          
          command: PowerToggle
          device: Fireplace
      turn_off:
        service: remote.send_command
        target:
          entity_id: remote.living_room
        data:          
          command: PowerToggle
          device: Fireplace
      icon_template: >-
        {% if is_state('remote.living_room', 'Fireplace') %}
          mdi:fireplace
        {% else %}
          mdi:fireplace-off
        {% endif %}

        # Fireplace
    
    # Office Heater
    office_heater:
      friendly_name: "Office Heater"
      value_template: "{{ is_state('remote.office', 'Heater') }}"
      turn_on:
        service: remote.send_command
        target:
          entity_id: remote.office
        data:          
          command: PowerToggle
          device: "Pelonis Climate Control"
      turn_off:
        service: remote.send_command
        target:
          entity_id: remote.office
        data:          
          command: PowerToggle
          device: "Pelonis Climate Control"
      icon_template: >-
        {% if is_state('remote.living room', 'Heater') %}
          mdi:radiator
        {% else %}
          mdi:radiator-diisabled
        {% endif %}

# Front Door
- platform: mqtt
  name: Front Door
  state_topic: "sonoff/stat/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "sonoff/cmnd/POWER1"
  availability_topic: "sonoff/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

# Wake On LAN
- platform: wake_on_lan
  name: Office PC
  mac: !secret mac_officepc
  host: !secret ip_officepc
