title: Apartment

resources:
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /local/mini-media-player-bundle.js?v=1.1.3
    type: module
  - url: /local/roku-card.js?v=0
    type: module

background: "#303030"

views:
  # Dashboard View
  - title: DASHBOARD
    icon: mdi:home
    theme: darkcyan
    cards:
      - type: weather-forecast
        entity: weather.dark_sky

      - type: horizontal-stack
        cards:
          # Main Lights
          - type: entity-button
            entity: light.main
            name: Apartment Lights On
            icon: mdi:lightbulb
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.main_lights_on
            hold_action:
              action: more-info

          # All Lights Off
          - type: entity-button
            entity: group.all_lights_simple
            name: All Lights Off
            icon: mdi:lightbulb-outline
            tap_action:
              action: call-service
              service: homeassistant.turn_off
              service_data:
                entity_id: group.all_lights_simple

          # Front Door Open
          - type: entity-button
            entity: binary_sensor.front_door_sensor
            name: Front Door
            icon: mdi:door
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.front_door

      # Space Heater
      - type: conditional
        conditions:
          - entity: binary_sensor.space_heater_connected
            state: "on"
        card:
          type: horizontal-stack
          cards:
            - type: entity-button
              entity: switch.space_heater_switch
              tap_action:
                action: toggle
            - type: entity-button
              entity: script.heater_power
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.heater_power
            - type: entity-button
              entity: script.heater_mode
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.heater_mode

      # Thermostat
      - type: thermostat
        entity: climate.apartment_thermostat
        name: Apartment

  # Lights View
  - title: Lights
    icon: mdi:lightbulb-on
    theme: darkcyan
    cards:
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.all_lights
          - type: light
            name: Main Lights
            entity: light.main
      - type: glance
        title: Rooms
        entities:
          - entity: group.kitchen_lights
            name: Kitchen Lights
            icon: mdi:lightbulb
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.kitchen_lights
          - entity: group.living_room_lights
            name: Living Room Lights
            icon: mdi:lightbulb
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.living_room_lights
          - entity: group.office_lights
            name: Office Lights
            icon: mdi:lightbulb
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.office_lights
          - entity: group.bedroom_lights
            name: Bedroom Lights
            icon: mdi:lightbulb
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.bedroom_lights
      # Scenes
      - type: glance
        title: Scenes
        entities:
          - entity: scene.normal
            name: Normal
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.normal
          - entity: scene.purple_chill
            name: Purple Chill
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.purple_chill
          - entity: scene.urban_temple
            name: Urban Temple
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.urban_temple
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.kitchen
          - type: light
            entity: light.living_room
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.office
          - type: light
            entity: light.bedroom
      - type: light
        entity: light.accent_lights

      # Lights list
      - type: entities
        show_header_toggle: false
        title: Lights
        entities:
          - type: section
            label: Kitchen
          - entity: light.kitchen_left_front
            name: Left Front
          - entity: light.kitchen_right_front
            name: Right Front
          - entity: light.kitchen_rear
            name: Rear
          - entity: light.entry
            name: Entry

          - type: section
            label: Living Room
          - entity: light.living_room_hanging
            name: Hanging
          - entity: light.living_room_dome_left
            name: Dome Left
          - entity: light.living_room_dome_right
            name: Dome Right
          - entity: light.hallway
            name: Hallway

          - type: section
            label: Accent
          - light.nanoleaf
          - entity: light.living_room_bloom
            name: Bloom
          - entity: light.living_room_tv
            name: TV

          - type: section
            label: Office
          - entity: light.office_dome_left
            name: Dome Left
          - entity: light.office_dome_right
            name: Dome Right
          - entity: light.office_lamp_top
            name: Lamp Top
          - entity: light.office_lamp_bottom
            name: Lamp Bottom

          - type: section
            label: Bedroom
          - entity: light.bedroom_light_1
            name: Dome 1
          - entity: light.bedroom_light_2
            name: Dome 2

  # Media View
  - title: Media
    icon: mdi:play-circle
    theme: darkcyan
    cards:
      - type: "custom:mini-media-player"
        entity: media_player.spotify
      - type: "custom:mini-media-player"
        entity: media_player.bedroom_chromecast

      - type: entities
        entities:
          - entity: switch.bedroom_tv
            icon: mdi:television

      - type: entities
        title: Harmony
        show_header_toggle: false
        entities:
          - input_select.living_room_hub
          - script.receiver_vol_up
          - script.receiver_vol_down
          - switch.pc_outlet
          - script.pc_power

      - type: "custom:roku-card"
        entity: media_player.living_room_roku
        name: Roku
        tv: true
        power:
          service: remote.turn_on
          service_data:
            entity_id: remote.living_room
            activity: Watch Roku

  # Camera View
  - title: Camera
    icon: mdi:cctv
    theme: darkcyan
    cards:
      - type: picture-glance
        entities:
          - switch.living_room_camera
        title: Living Room
        camera_image: camera.living_room
        camera_view: live

  # Status View
  - title: Network
    icon: mdi:server-network
    theme: darkcyan
    cards:
      # Device Status
      - type: glance
        title: Device Status
        entities:
          - entity: sensor.memory_use_percent
            name: Memory Use
          - entity: sensor.disk_use_percent_home
            name: Disk Use
          - entity: sensor.last_boot
            name: Restart Hass
            icon: mdi:restart
            tap_action:
              action: call-service
              service: homeassistant.restart

      # Network Status
      - type: glance
        title: Network Status
        entities:
          - entity: binary_sensor.network
            hold_action:
              action: call-service
              service: automation.trigger
              service_data:
                entity_id: automation.restart_modem
          - entity: binary_sensor.google_home
          - entity: sensor.speedtest_ping
            name: Ping
          - entity: sensor.speedtest_upload
            name: Upload
          - entity: sensor.speedtest_download
            name: Download

  # Settings View
  - title: Settings
    icon: mdi:settings
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - entity: automation.front_door_open
            name: Front Door - Lights
