- alias: Front Door Open
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.sensor.entrance_dimmer_switch.last_updated)) > 5 }}"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: light.kitchen
          value_template: '{% if states.light.kitchen.state == "on"  %}{{ states.light.kitchen.attributes.brightness }}{% else %}0{% endif %}'
          below: 120
        - condition: numeric_state
          entity_id: light.kitchen
          value_template: >
            {% if state_attr('light.kitchen', 'color_temp') %}
              {{ states.light.kitchen.attributes.color_temp }}
            {% else %}
              0
            {% endif %}
          below: 365
          above: 400        
  action:
    - service: switch.turn_on
      entity_id:
        - switch.kitchen_light_switch
    - service: light.turn_on
      entity_id:
        - light.kitchen
      data:
        brightness: 120
        kelvin: 2700

- alias: Balcony Door Open
  trigger:
    platform: state
    entity_id: binary_sensor.balcony_door_sensor
    to: "on"
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.thermostat
        hvac_mode: "off"
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -5 }}"
    - service: light.turn_on
      target:
        entity_id: light.balcony_lightstrip

- alias: Balcony Door Closed
  trigger:
    platform: state
    entity_id: binary_sensor.balcony_door_sensor
    to: "off"
  action:
    - service: climate.set_hvac_mode
      data_template:
        entity_id: climate.thermostat
        hvac_mode: >
          {% if states('sensor.compare_temp_current_target') | float > 0 %}
            cool
          {% elif states('sensor.compare_temp_current_target') | float < 0 %}
            heat
          {% else %}
            heat_cool
          {% endif %}
    - service: light.turn_off
      target:
        entity_id: light.balcony_lightstrip

