- alias: "Entrance Dimmer ON"
  trigger:
    - platform: state
      entity_id: sensor.entrance_dimmer_switch
      to: "1_click"
    - platform: state
      entity_id: sensor.entrance_dimmer_switch
      to: "1_click_up"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.kitchen_light_switch
        - switch.living_room_chandelier
        - switch.living_room_dome

- alias: "Entrance Dimmer OFF"
  trigger:
    - platform: state
      entity_id: sensor.entrance_dimmer_switch
      to: "4_click"
    - platform: state
      entity_id: sensor.entrance_dimmer_switch
      to: "4_click_up"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights_simple
        - remote.living_room
        - switch.space_heater_switch

- alias: "Office Dimmer ON"
  trigger:
    - platform: state
      entity_id: sensor.office_dimmer_switch
      to: "1_click"
    - platform: state
      entity_id: sensor.office_dimmer_switch
      to: "1_click_up"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.office_light_switch

- alias: "Office Dimmer OFF"
  trigger:
    - platform: state
      entity_id: sensor.office_dimmer_switch
      to: "4_click"
    - platform: state
      entity_id: sensor.office_dimmer_switch
      to: "4_click_up"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.lava_lamp
