- alias: "Entrance Dimmer (On)"
  id: c7fd9a4b-9ef0-4b53-83b9-5b59e1d3c031
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: entrance_dimmer_switch_button
        type: short_release
        subtype: 1
  action:
    - service: homeassistant.turn_on
      target:
        entity_id:
          - switch.kitchen_light_switch
          - switch.living_room_chandelier
          - switch.living_room_dome
          - scene.kitchen_normal

- alias: "Entrance Dimmer (Off)"
  id: 7a254108-654c-48f8-95ee-2569c658b9e9
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: entrance_dimmer_switch_button
        type: short_release
        subtype: 4
  action:
    - service: homeassistant.turn_off
      target:
        entity_id:
          - group.all_lights_simple
          - remote.living_room
          - switch.space_heater_switch

- alias: "Office Dimmer (On)"
  id: 715074dd-0ef6-4aff-b4f6-f77cea63f9aa
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: office_dimmer_switch_button
        type: short_release
        subtype: 1
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.office_light_switch

- alias: "Office Dimmer (Off)"
  id: e2af5c39-b91b-4b63-97bd-66292f3224ca
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: office_dimmer_switch_button
        type: short_release
        subtype: 4
  action:
    - service: homeassistant.turn_off
      target:
        entity_id:
          - switch.lava_lamp
