- alias: IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
  action:
    service: "{{ trigger.event.data.service }}"
    data:
      entity_id: "{{ trigger.event.data.entity_id }}"
