- alias: "Office Lights On"
  id: e29c4cf2-662f-4494-817e-181c5051eaaa
  trigger:
    platform: state
    entity_id: switch.office_light_switch
    from: "off"
    to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.office_lamp_top,light.office_lamp_bottom
        brightness: 255
        kelvin: 2700

- alias: "Office Lights Off"
  id: c6d0a0cf-2752-4884-8bac-ec146235fa4e
  trigger:
    platform: state
    entity_id: switch.office_light_switch
    from: "on"
    to: "off"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - light.office_lamp_top
          - light.office_lamp_bottom
          - light.desk_lightstrip
          - switch.lava_lamp
