- alias: "Turn on office lamp with wall switch"
  trigger:
    platform: state
    entity_id: switch.office_light_switch
    from: "off"
    to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.office_lamp_top,light.office_lamp_bottom
        brightness: 255
        kelvin: 2700

- alias: "Turn off office lights with wall switch"
  trigger:
    platform: state
    entity_id: switch.office_light_switch
    from: "on"
    to: "off"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - light.office_lamp_top
          - light.office_lamp_bottom
          - light.desk_lightstrip
          - switch.lava_lamp
