- alias: "Bedroom TV Auto Off"
  trigger:
    platform: state
    entity_id: media_player.bedroom_chromecast
    to: 'off'
    for:
      minutes: 5
  action:
    service: switch.turn_off
    entity_id: switch.bedroom_tv

- alias: "Bedroom Chromecast Auto Off"
  trigger:
    platform: state
    entity_id: switch.bedroom_tv
    to: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.bedroom_chromecast

- alias: "Bedroom TV playing"
  trigger: 
    platform: state
    entity_id: media_player.bedroom_chromecast
    to: 'playing'
  condition:
    - condition: numeric_state
      entity_id: light.bedroom
      value_template: '{% if states.light.bedroom.state == "on"  %}{{ states.light.bedroom.attributes.brightness }}{% else %}0{% endif %}'
      above: 150
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness: 150
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_chromecast
        volume_level: 0.5