- alias: "Bedroom TV Auto Off"
  id: 7dabd790-7214-4577-935b-1799e58ea068
  trigger:
    platform: state
    entity_id: media_player.bedroom_chromecast
    to: "off"
    for:
      minutes: 5
  action:
    service: media_player.turn_off
    entity_id: media_player.bedroom_chromecast

- alias: "Bedroom Chromecast Start"
  id: 206c1328-dde1-4cce-885b-1c532a87c3f6
  trigger:
    platform: state
    entity_id: media_player.bedroom_chromecast
    to: "playing"
  condition:
    - condition: numeric_state
      entity_id: light.bedroom_lights
      value_template: '{% if states.light.bedroom_lights.state == "on"  %}{{ states.light.bedroom_lights.attributes.brightness }}{% else %}0{% endif %}'
      above: 150
  action:
    - service: light.turn_on
      data:
        brightness: 150
      target:
        entity_id:
          - light.bedroom_light_1
          - light.bedroom_light_2
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_chromecast
        volume_level: 0.5

- alias: "Sync Harmony with Living Room Chromecast"
  id: 73b078dc-1f3a-4b49-9ff1-e5173b41489f
  trigger:
    - platform: state
      entity_id: media_player.living_room_chromecast
      to: "playing"
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: "Watch Google TV"
    - condition: "{{ state_attr('light.living_room','brightness') > 160 }}"
    - service: scene.turn_on
      target:
        entity_id:
          - scene.kitchen_dimmed
          - scene.living_room_dimmed
