- alias: Restart modem
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.network
      to: "off"
  action:
    - service: notify.ios_the_ijarvis
      data:
        title: "Network down"
        message: "Restarting modem"
    - service: switch.turn_off
      data:
        entity_id: switch.modem
    - delay:
        seconds: 5
    - service: switch.turn_on
      data:
        entity_id: switch.modem
