- alias: Away

  trigger:
    platform: state
    entity_id: binary_sensor.anthony_home
    from: "on"
    to: "off"
    for:
      minutes: 15
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights_simple
        - remote.living_room
        - switch.space_heater_switch
    - service: homeassistant.turn_on
      entity_id:
        - camera.living_room

- alias: Home

  trigger:
    platform: state
    entity_id: binary_sensor.anthony_home
    from: "off"
    to: "on"
  action:
    - service: camera.turn_off
      entity_id: camera.living_room