- alias: Away
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.anthony_home
    from: "on"
    to: "off"
    for:
      minutes: 15
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights_simple
        - remote.living_room
        - switch.space_heater_switch
    - service: homeassistant.turn_on
      entity_id:
        - camera.living_room

- alias: Home
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.anthony_home
    from: "off"
    to: "on"
  action:
    - service: camera.turn_off
      entity_id: camera.living_room

- alias: Guest Mode On
  trigger:
    platform: state
    entity_id: input_boolean.guests
    to: "on"
  action:
    - service: automation.turn_off
      entity_id:
        - automation.front_door_open
        - automation.away

- alias: Guest Mode Off
  trigger:
    platform: state
    entity_id: input_boolean.guests
    to: "off"
  action:
    - service: automation.turn_on
      entity_id:
        - automation.front_door_open
        - automation.away
