- alias: "Sync Harmony with Living Room Chromecast"
  id: 73b078dc-1f3a-4b49-9ff1-e5173b41489f
  trigger:
    - platform: state
      entity_id: media_player.living_room_chromecast
      to: "playing"
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: "Watch Google TV"
    - condition: "{{ state_attr('light.living_room','brightness') > 160 }}"
    - service: scene.turn_on
      target:
        entity_id:
          - scene.kitchen_dimmed
          - scene.living_room_dimmed
