- alias: Harmony
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.living_room_hub
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.living_room_hub", "Watch PC") %}
            Watch PC
          {% elif is_state("input_select.living_room_hub", "Watch Roku") %}
            Watch Roku
          {% elif is_state("input_select.living_room_hub", "Listen to Music") %}
            Listen to Music
          {% elif is_state("input_select.living_room_hub", "Power Off") %}
            PowerOff
          {% endif %}

- alias: Harmony Off
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.living_room_hub
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.living_room

- alias: "Start - Update Harmony status"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: remote.living_room
    - platform: homeassistant
      event: start
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.living_room_hub
      option: >
        {% if is_state_attr('remote.living_room','current_activity','PowerOff') %}
          Power Off
        {% else %}
          {{ state_attr('remote.living_room','current_activity') }}
        {% endif %}
