- alias: Front Door Button
  id: 80abea63-18ce-4079-98f2-63c1999bac0c
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.front_door_button
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.front_door_button
        click_type: long_click_press
  action:
    service: script.open_front_door
